/* Write your T-SQL query statement below */
SELECT
A.MACHINE_ID,
ROUND(AVG(B.TIMESTAMP-A.TIMESTAMP),3) AS PROCESSING_TIME
FROM ACTIVITY AS A 
JOIN 
ACTIVITY AS B
ON A.PROCESS_ID=B.PROCESS_ID
AND A.MACHINE_ID=B.MACHINE_ID
AND A.TIMESTAMP<B.TIMESTAMP
GROUP BY A.MACHINE_ID