/* Write your T-SQL query statement below */
WITH CTE AS(
    SELECT
    A.MACHINE_ID,
    (B.TIMESTAMP-A.TIMESTAMP)AS PROCESSING_TIME
    FROM ACTIVITY AS A
    JOIN 
    ACTIVITY AS B
    ON A.PROCESS_ID =B.PROCESS_ID
    AND  A.MACHINE_ID=B.MACHINE_ID
    AND A.ACTIVITY_TYPE='START'
    AND B.ACTIVITY_TYPE='END'
)
SELECT
MACHINE_ID,
ROUND(AVG(PROCESSING_TIME),3) AS PROCESSING_TIME
FROM CTE
GROUP BY MACHINE_ID