/* Write your T-SQL query statement below */
WITH UNBANNED AS (
    SELECT USERS_ID FROM USERS
    WHERE BANNED='NO'
)

SELECT 
REQUEST_AT AS DAY,
ROUND(SUM(CASE WHEN STATUS LIKE 'CANCELLED%'
            THEN 1.00
            ELSE 0 END)/COUNT(*),2
            ) AS 'CANCELLATION RATE'
    FROM TRIPS
WHERE
CLIENT_ID IN(SELECT USERS_ID FROM UNBANNED)
AND DRIVER_ID IN(SELECT USERS_ID FROM UNBANNED)
AND REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY REQUEST_AT