/* Write your T-SQL query statement below */
WITH CTE AS(
    SELECT 
    PLAYER_ID,
    EVENT_DATE,
    RANK() OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS RANK
    FROM ACTIVITY
)
SELECT
PLAYER_ID,
EVENT_DATE AS FIRST_LOGIN
FROM CTE WHERE RANK=1
